export const FETCH_USER_INCREMENTAL_INIT = "FETCH_USER_INCREMENTAL_INIT";
export const FETCH_USER_INCREMENTAL_SUCCESS = "FETCH_USER_INCREMENTAL_SUCCESS";
export const FETCH_USER_INCREMENTAL_FAIL = "FETCH_USER_INCREMENTAL_FAIL";

export const SAGA_FETCH_USER_INIT = "SAGA_FETCH_USER_INIT";
export const SAGA_FETCH_USER_SUCCESS = "SAGA_FETCH_USER_SUCCESS";
export const SAGA_FETCH_USER_FAIL = "SAGA_FETCH_USER_FAIL";
