export const FETCH_USER_INCREMENTAL_INIT = "FETCH_USER_INCREMENTAL_INIT";
export const FETCH_USER_INCREMENTAL_SUCCESS = "FETCH_USER_INCREMENTAL_SUCCESS";
export const FETCH_USER_INCREMENTAL_FAIL = "FETCH_USER_INCREMENTAL_FAIL";

export const SAGA_FETCH_USER_INIT = "SAGA_FETCH_USER_INIT";
export const SAGA_FETCH_USER_SUCCESS = "SAGA_FETCH_USER_SUCCESS";
export const SAGA_FETCH_USER_FAIL = "SAGA_FETCH_USER_FAIL";

export const SAGA_FETCH_USER_WITH_TIMEOUT_INIT =
  "SAGA_FETCH_USER_WITH_TIMEOUT_INIT";
export const SAGA_FETCH_USER_TIMEOUT_ERROR = "SAGA_FETCH_USER_TIMEOUT_ERROR";

export const SAGA_FETCH_TWO_USERS_RACE = "SAGA_FETCH_TWO_USERS_RACE";
export const FIRST_USER_WINS = "FIRST_USER_WINS";
export const SECOND_USER_WINS = "SECOND_USER_WINS";

export const EXPENSIVE_TASK_INIT = "EXPENSIVE_TASK_INIT";
export const EXPENSIVE_TASK_COMPLETED = "EXPENSIVE_TASK_COMPLETED";
export const EXPENSIVE_TASK_CANCEL = "EXPENSIVE_TASK_CANCEL";
export const EXPENSIVE_TASK_CANCELED = "EXPENSIVE_TASK_CANCELED";
